### ISSUE TITLE
No module named SR_DenseNet

### ISSUE THREAD

**Issue by jeejeelee** [wxywhu/SRDenseNet-pytorch#2]
Hi:
thanks for sharing your impressive job, I want to evaluate  perfermance in test.py ,I have downloaded your shared model , I encounter a error"No module named SR_DenseNet",but I can't find this class in this repo,can you add it ?thanks very much

**Comment by wxywhu** [comment]
@jeejeeli
Sorry, i add the module named SR_DenseNet and the pre-trained model is trained using it. However, i found the code is rather redundant and revised it as SR_DenseNet

**Comment by jeejeelee** [comment]
@wxywhu  Thanks very much
