### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by ShinoSpace** [wxywhu/SRDenseNet-pytorch#6]
Thanks for your code first!
I‘d like to ask the input and out put, which puzzled me for a long time.
1. Do you pre-process your input image? such as normalization.
2. About the output scale. For instance, if the input image is 25 x 25, then i'll finally get 100 x 100 output only in Y channel. If i want to visualize the output, the Cb and Cr channel need to be concatenate with output, but Cb and Cr channel of input LR is 25 x 25. I guess you use the bicubic interpolation to resize the Cb Cr to 100 x 100, is that correct?
I am a green hand in DL and CV, so maybe some question may stupid. I'll very appreciate if you can solve my problem. Thank you!

**Comment by wxywhu** [comment]
@ErrorIsland 
Yes, you can find that in generate_train.m and the function im2double() would not only converts image to double type but also maps data from 0 to 255 to 0 to 1.
As for the second question, you are right and you can find this technique in some paper for super-resolution.

**Comment by ShinoSpace** [comment]
Greatly thanks to your answer!
